<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Document</title>
</head>
<body>
    <h1>Bienvenido <?php echo $_SESSION['user']->getUsername(); ?></h1>
    <h1>CREAR ARTICULO</h1>
    <form action="index.php" method="post">
        <label for="title">Titulo:</label>
        <input type="text" id="title" name="title">
        <br>
        <label for="text">Contenido:</label>
        <textarea id="text" name="text"></textarea>
        <br>
        <input type="submit" value="Guardar" name="Guardar">
    </form>
    <br>
    <a href='index.php?c=article'>Volver</a>
    
</body>
</html>