<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Document</title>
    <link rel="stylesheet" href="styles/styles.css">
</head>
<body>
    <h1>Comentarios</h1>
    <form action="index.php?c=article&a=addComment&id=<?php echo $_GET['id']; ?>" method="post">
        <label for="text">Comentario:</label>
        <textarea id="text" name="text"></textarea>
        <br>
        <input type="submit" value="Guardar" name="Guardar">
    </form>
    <br>
    <a href='index.php?c=article'>Volver</a>
</body>
</html>