<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Document</title>
    <link rel="stylesheet" href="styles/styles.css">
</head>
<body>  
    <h1>LOGIN</h1>
        <form action="index.php" method="post">
        <label for="username">Usuario:</label>
        <input type="text" id="username" name="username">
        <br>
        <label for="password">Contraseña:</label>
        <input type="password" id="password" name="password">
        <br>
        <input type="submit" value="Enviar" name="Enviar">
        <input type="submit" value="Registrar" name="Registrar">
        </form>
</body>
</html>
